build:
  image: bjodah/bjodahimg:v1.1
  commands:
    - cd tests
    - make
    - make -B CXX=clang++-3.7
    - make -B RELEASE=1
    - make -B CXX=clang++-3.7 RELEASE=1
    - cd -
    - ./scripts/ci.sh symcxx
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: symcxx
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
