build:
  image: bjodah/bjodahimg16:v1.2
  commands:
    - cd tests; make; cd -
    - ./scripts/ci.sh symcxx
    - cd tests; make -B CXX=clang++-3.8 DEFINES=-DNDEBUG; cd -
    - cd tests; make -B CXX=clang++-3.8 RELEASE=1; cd -
    - cd tests; make -B RELEASE=1; cd -
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: symcxx
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
