pipeline:
  build:
    image: bjodah/bjodahimg20dev:v1.0.5
    commands:
      - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
      - cd tests; make -B CXX=g++-10; cd -
      - ./scripts/ci.sh symcxx
      - export CPLUS_INCLUDE_PATH=$(pwd)/include
      - cd tests && make -B CXX=g++-10     CXXFLAGS="-D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -Werror -Og -ggdb3 -UNDEBUG" && cd -
      - cd tests && make -B CXX=clang++-10 CXXFLAGES=-fsanitize=address && cd -
      - cd tests && make -B CXX=clang++-10 CXXFLAGES="-fsanitize=undefined  -g -fsized-deallocation" && cd -
      - cd tests && make -B CXX=clang++-10 CXXFLAGES="-fsanitize=MemoryWithOrigins -fsized-deallocation -fno-optimize-sibling-calls -glldb -stdlib=libc++ -I/opt/libcxx10_msan/include -I/opt/libcxx10_msan/include/c++/v1" LDFLAGS="-Wl,-rpath,/opt/libcxx10_msan/lib -L/opt/libcxx10_msan/lib -lc++abi" test && cd -
      - cd tests && make -B CXX=clang++-10 CXXFLAGS="-DNDEBUG -O2" && cd -
      - cd tests && make -B RELEASE=1 && cd -
      - ./scripts/prepare_deploy.sh
      - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi
  
  deploy:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "hera.physchem.kth.se" ]
    port: 22
    user: symcxx
    secrets: [ rsync_key ]  # secret only set from event "push" not "pull_request"
    source: ./deploy/public_html
    target: ~/
