build:
  image: bjodah/bjodahimg16dev:latest
  commands:
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - cd tests; make; cd -
    - ./scripts/ci.sh symcxx
    - cd tests; make -B CXX=clang++-3.8 CXXFLAGES=-fsanitize=address; cd -
    - cd tests; make -B CXX=clang++-3.8 RELEASE=1; cd -
    - cd tests; make -B RELEASE=1; cd -
    - ./scripts/prepare_deploy.sh
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: symcxx
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
