SYMCXX_TYPE(Sub    , Binary   , sub    )
SYMCXX_TYPE(Div    , Binary   , div    )
SYMCXX_TYPE(Add2   , Binary   , add2   )
SYMCXX_TYPE(Mul2   , Binary   , mul2   )
#include "symcxx/types_nonatomic_binary_math_h.inc"
SYMCXX_TYPE(Lt     , Binary   , lt     ) // All after (incl.) Lt are relational
SYMCXX_TYPE(Le     , Binary   , le     )
SYMCXX_TYPE(Eq     , Binary   , eq     )
SYMCXX_TYPE(Ne     , Binary   , ne     )
SYMCXX_TYPE(Ge     , Binary   , ge     )
SYMCXX_TYPE(Gt     , Binary   , gt     )
