{% set name = "symcxx" %}
{% set version = "0.2.0.git" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - numpy
    - mako
    - cython ==0.23.4
  run:
    - python
    - numpy
    - libgcc

test:
  imports:
    - {{ name }}

  requires:
    - pytest
    - numpy

  commands:
    - py.test --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Fast symbolic manipulation in Python.'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
