package:
  name: symcxx
  version: 0.2.0.git

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - mako
    - cython ==0.23.4
  run:
    - python
    - numpy

test:
  imports:
    - symcxx

  requires:
    - pytest
    - numpy

  # commands:
  #   - py.test --pyargs symcxx

about:
  home: https://github.com/bjodah/symcxx
  license: BSD
  summary: fast symbolic manipulation in Python
